logging:
  level.org.springframework: INFO
spring:
  datasource:
    url: jdbc:hsqldb:mem:dataSource
    username: sa
    password:
---
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/quiz
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect